### ISSUE TITLE
Joomla update available. Installed version: 3.10.0. Can be updated to 3.2.7

### ISSUE THREAD

**Issue by 47k** [lucasaba/check_joomla#3]
Hello 

I think there is something wrong with the current version numbers:
Joomla update available. Installed version: 3.10.0. Can be updated to 3.2.7

It happens since 3.10.0 - with 3.9.x is was fine.

**Comment by lucasaba** [comment]
Thank you very much @47k for pointing that out.I'll give it a check.

**Comment by lucasaba** [comment]
Hi @47k ,
I've made a complete rewrite of the script.

Would you mind testing the new script ?

You can simply overwrite your current script with this: https://github.com/lucasaba/check_joomla/blob/final-zero-bug/check_joomla

I've added some manual test just to prevent the situation you've mentioned. I've tested it against my Joomla installations and it works... but a second check would be very appreciated!

**Comment by 47k** [comment]
Hey - I tested it on my Joomla installations and I got the result "No update available for your current Joomla version: 3.10.0" and this one for an older version: "Joomla update available. Installed version 3.9 can be updated to 3.10.0" 

Thank you for your very fast work! :) Don't forget to upgrade it on the Nagios Exchange if necessary.
