### ISSUE TITLE
The local installed version has only x.xx Version number instead of x.xx.x 

### ISSUE THREAD

**Issue by 47k** [lucasaba/check_joomla#5]
Installed version 3.10 can be updated to 3.10.4 but the installed version is 3.10.2. I think it's the same fix from the available version (before it was the same).

**Comment by lucasaba** [comment]
I'll check! Thanks for the issue ;)

**Comment by lucasaba** [comment]
@47k could please check if the problem has been fixed ? I've updated the release and published it. It's 1.0.1

**Comment by 47k** [comment]
It's working as expected: Joomla update available. Installed version 3.10.3 can be updated to 3.10.4
Thank you for the fast fix! :)
