### ISSUE TITLE
wrong version

### ISSUE THREAD

**Issue by w3bservice** [lucasaba/check_joomla#7]
Joomla update available. Installed version 4.1.1 can be updated to 4.1.0

**Comment by lucasaba** [comment]
Thanks @w3bservice il check it as soon as possible!

**Comment by lucasaba** [comment]
@w3bservice should be fixed. Would you please give me a feedback if it works as expected ?

**Comment by w3bservice** [comment]
@lucasaba Sorry I didn't answer, I was sick. Your change worked. Thank you. Great work

**Comment by lucasaba** [comment]
Thanks @w3bservice !
